FROM node:latest as packages
WORKDIR /packages
COPY . package.json
RUN yarn

FROM node:latest
COPY . /
WORKDIR /beverage/back-end
COPY --from=packages /packages/node_modules /back-end/node_modules
ENTRYPOINT ["yarn", "dev"]
EXPOSE 4000