FROM node:latest as packages
WORKDIR /packages
COPY package.json .
RUN yarn

FROM node:latest
COPY . /back-end
WORKDIR /Beverage/back-end
COPY --from=packages /packages/node_modules /TesteTDDRocketSeat1/node_modules
ENTRYPOINT ["yarn", "start"]
EXPOSE 4000