FROM node:latest as packages
WORKDIR /packages
COPY . package.json
RUN yarn

FROM node:latest
COPY . /web
WORKDIR /beverage/web
COPY --from=packages /packages/node_modules /web/node_modules
RUN yarn global add esbuild
ENTRYPOINT ["yarn", "dev"]
EXPOSE 3000